### ISSUE TITLE
`mkinitcpio` file or directory not exists

### ISSUE THREAD

**Issue by tino415** [EvoLutionLinux/archiso#2]
When I tried to build basic archlinux iso, I get this error,
it is `releng` but I deleted all packages in packages.both and added `wpa_supplicant` so mi packages.both is 

```
wpa_supplicant
```

```
[mkarchiso] INFO: Configuration settings
[mkarchiso] INFO:                   Command:   run
[mkarchiso] INFO:              Architecture:   i686
[mkarchiso] INFO:         Working directory:   work/i686
[mkarchiso] INFO:    Installation directory:   arch
[mkarchiso] INFO:               Run command:   mkinitcpio -c /etc/mkinitcpio-archiso.conf -k /boot/vmlinuz-linux -g /boot/archiso.img

chroot: failed to run command \`mkinitcpio': Directory or file not exists
```

**Comment by EvoLutionLinux** [comment]
Hi,

That's likely because I've removed 32 bit architecture from the archiso profile in makeiso. Try it for x86_64 rather than i686. Adding 32 bit support doubles the size of the iso's unless you remove the 64 bit capacity.

It's been quite a while since I've worked on Makeiso as I'm just now recovering from some brutal cancer treatment. I may get back into it soon though. I've been contemplating on incorporating rsync as a major part of makeiso.  See https://sites.google.com/site/evolutionlinux9088/home for future status.

If you want to add 32 bit capacity back to your archiso profile, see the archiso section in the arch wiki. 

---

On Sun, 10/16/16, tino415 notifications@github.com wrote:

 Subject: [EvoLutionLinux/archiso] `mkinitcpio` file or directory not exists (#2)
 To: "EvoLutionLinux/archiso" archiso@noreply.github.com
 Date: Sunday, October 16, 2016, 12:16 PM

 When I tried to build basic
 archlinux iso, I get this error,

 it is releng but I deleted all packages in
 packages.both and added wpa_supplicant so mi
 packages.both is 

 wpa_supplicant

 [mkarchiso] INFO: Configuration settings
 [mkarchiso] INFO:                   Command:   run
 [mkarchiso] INFO:              Architecture:   i686
 [mkarchiso] INFO:         Working directory:   work/i686
 [mkarchiso] INFO:    Installation directory:   arch
 [mkarchiso] INFO:               Run command:   mkinitcpio -c
 /etc/mkinitcpio-archiso.conf -k /boot/vmlinuz-linux -g
 /boot/archiso.img

 chroot: failed to run command `mkinitcpio':
 Directory or file not exists

 —
 You are receiving this because you are subscribed to this
 thread.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.

**Comment by tino415** [comment]
Thank you, I just dont have enought network to download archlinux iso so I need to generate som functional live for 32 bit PC to rescue it, since then problem is solved and I have backed ready to use iso, probabli just add some message that describe issue for user would by enought and I'm sorry about the cancer but glad that you are after (I assume you are ok now)

**Comment by crackedpotato007** [comment]
```
[mkarchiso] INFO: Configuration settings
[mkarchiso] INFO:                   Command:   run
[mkarchiso] INFO:              Architecture:   x86_64
[mkarchiso] INFO:         Working directory:   work
[mkarchiso] INFO:    Installation directory:   arch
[mkarchiso] INFO:               Run command:   mkinitcpio -c /etc/mkinitcpio-archiso.conf -k /boot/vmlinuz-linux -g /boot/archiso.img

```

Error
```
==> WARNING: work/root-image is not a mountpoint. This may have undesirable side effects.
chroot: failed to run command 'mkinitcpio': No such file or directory
```
